export const GUARDIAN_TIPS = [
  {
    id: 'sos',
    text: 'Tap the shield anytime for instant SOS.',
    icon: '🛡️',
    action: 'navigate',
    target: '/emergency',
  },
  {
    id: 'emergency_pin',
    text: 'Lost your phone? Use your Emergency PIN.',
    icon: '🔐',
    action: 'navigate',
    target: '/emergency-access',
  },
  {
    id: 'guardian_view',
    text: 'Family can track you live via Guardian View.',
    icon: '👁️',
    action: 'navigate',
    target: '/emergency',
  },
  {
    id: 'passport_vault',
    text: 'Your passport is encrypted in your Vault.',
    icon: '🗄️',
    action: 'navigate',
    target: '/passport-vault',
  },
  {
    id: 'solo_checkin',
    text: 'Solo traveler? Check in every 8-12 hours.',
    icon: '❤️',
    action: 'navigate',
    target: '/dashboard',
  },
  {
    id: 'baggage',
    text: 'Tag your bags — track them anywhere offline.',
    icon: '🧳',
    action: 'navigate',
    target: '/dashboard/documents',
  },
  {
    id: 'handshake',
    text: 'Every transfer is logged with iQ200 handshake.',
    icon: '🤝',
    action: 'navigate',
    target: '/dashboard/journey',
  },
  {
    id: 'activity_safety',
    text: 'Register activities before you go — stay safe.',
    icon: '🏄',
    action: 'navigate',
    target: '/safe-t',
  },
  {
    id: 'offline',
    text: 'No signal? The app works fully offline.',
    icon: '📡',
    action: 'navigate',
    target: '/offline',
  },
  {
    id: 'sos_translate',
    text: 'SOS auto-translates to the local language.',
    icon: '🌍',
    action: 'navigate',
    target: '/emergency',
  },
];