// @ts-nocheck — Base44 InvokeLLM SDK types don't yet expose system_prompt/response_type; runtime works correctly
/**
 * PreDepartureBriefing — AI-generated personalized safety brief
 *
 * Generated by LLM using the patient's destination, procedure, and live
 * EVN-iQ400 advisory data. Appears on the Dashboard before departure.
 * No other medical tourism platform generates a personalized AI safety
 * briefing for each patient before they travel.
 *
 * Props: caseRecord, userName
 */
import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, ChevronDown, ChevronUp, Globe, AlertTriangle, CheckCircle2, Loader2 } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { COUNTRY_ISO, getRiskLevel } from '@/hooks/useEnvironmentalIntelligence';
import { isSystemPaused } from '@/lib/systemPause';

const GOLD = '#D4AF37';

const CACHE_KEY = (caseId) => `morales_briefing_${caseId}`;
const CACHE_TTL = 12 * 60 * 60 * 1000; // 12h — refresh daily

function readBriefingCache(caseId) {
  try {
    const raw = localStorage.getItem(CACHE_KEY(caseId));
    if (!raw) return null;
    const { briefing, ts } = JSON.parse(raw);
    return (Date.now() - ts < CACHE_TTL) ? briefing : null;
  } catch { return null; }
}

function writeBriefingCache(caseId, briefing) {
  try {
    localStorage.setItem(CACHE_KEY(caseId), JSON.stringify({ briefing, ts: Date.now() }));
  } catch {}
}

// Offline fallback — generated from hardcoded templates when LLM unavailable
function offlineBriefing(country, procedure, evnScore) {
  const risk = evnScore ? getRiskLevel(evnScore) : null;
  return {
    threatLevel: risk?.label || 'Moderate',
    precautions: [
      'Always travel with your Morales emergency card accessible.',
      `Your Morales concierge has pre-arranged vetted transport in ${country}.`,
      'Keep your Emergency PIN memorised — accessible from any device without internet.',
      'Share your Guardian Link with a trusted family member before departure.',
    ],
    emergencyProtocol: `If you need immediate help in ${country}: (1) Press the SOS button in the Morales app. (2) Text HELP to your Morales shortcode. (3) Activate your Emergency PIN from any device. Your concierge will respond within 5 minutes.`,
    culturalNote: `Follow local dress codes and customs in ${country}. Your Morales guide has destination-specific guidance in the Knowledge Base (tap the ✨ orb).`,
    recoveryNote: procedure ? `After your ${procedure} procedure, follow the Morales post-op protocol. Your Day 3, 7, 14, and 30 check-ins are pre-scheduled.` : 'Follow your Morales post-op recovery timeline closely.',
    generatedBy: 'offline',
  };
}

export default function PreDepartureBriefing({ caseRecord, userName }) {
  const [open,     setOpen]     = useState(false);
  const [briefing, setBriefing] = useState(null);
  const [loading,  setLoading]  = useState(false);
  const [evnScore, setEvnScore] = useState(null);

  const country   = caseRecord?.procedure_country;
  const procedure = caseRecord?.procedure_interest;
  const caseId    = caseRecord?.id;
  const name      = userName?.split(' ')[0] || 'Traveller';

  // Fetch EVN-iQ400 score for destination
  useEffect(() => {
    if (!country) return;
    const iso2 = COUNTRY_ISO[country];
    if (!iso2) return;
    (async () => {
      try {
        const res  = await fetch('https://www.travel-advisory.info/api', { signal: AbortSignal.timeout(6000) });
        const json = await res.json();
        const entry = json?.data?.[iso2];
        if (!entry) return;
        const score = entry.advisory?.score ?? 2;
        setEvnScore(Math.round(((Math.max(1, Math.min(5, score)) - 1) / 4) * 85 + 5));
      } catch { setEvnScore(33); }
    })();
  }, [country]);

  // Generate briefing when user opens the card
  const generateBriefing = async () => {
    if (briefing) { setOpen(true); return; }

    // Check cache
    const cached = caseId ? readBriefingCache(caseId) : null;
    if (cached) { setBriefing(cached); setOpen(true); return; }

    setOpen(true);
    setLoading(true);

    // Offline fallback if system paused or no network
    if (!navigator.onLine || isSystemPaused()) {
      const fb = offlineBriefing(country, procedure, evnScore);
      setBriefing(fb);
      if (caseId) writeBriefingCache(caseId, fb);
      setLoading(false);
      return;
    }

    try {
      const evnLine = evnScore ? `Current EVN-iQ400 environmental risk score: ${evnScore}/100.` : '';
      const res = await base44.integrations.Core.InvokeLLM({
        prompt: `Generate a pre-departure safety briefing for a Morales Medical Concierge patient.
Patient: ${name}
Destination: ${country}
Procedure: ${procedure || 'medical procedure'}
${evnLine}

Respond with ONLY valid JSON (no markdown):
{
  "threatLevel": "Low|Moderate|Elevated|High",
  "precautions": ["3-4 specific, actionable safety precautions for this destination and procedure"],
  "emergencyProtocol": "2-3 sentences: what to do if the patient needs immediate help in this country",
  "culturalNote": "1-2 sentences: key cultural considerations for this destination",
  "recoveryNote": "1-2 sentences: procedure-specific recovery advice"
}

Be specific to ${country} and ${procedure || 'medical travel'}. Plain language. No generic filler.`,
        response_type: 'text',
      });

      const text  = typeof res === 'string' ? res : (res?.result || res?.text || '');
      const clean = text.replace(/```[\w]*\n?|\n?```/g, '').trim();
      let parsed;
      try {
        parsed = JSON.parse(clean);
        parsed.generatedBy = 'ai';
      } catch {
        parsed = offlineBriefing(country, procedure, evnScore);
      }

      setBriefing(parsed);
      if (caseId) writeBriefingCache(caseId, parsed);
    } catch {
      const fb = offlineBriefing(country, procedure, evnScore);
      setBriefing(fb);
      if (caseId) writeBriefingCache(caseId, fb);
    } finally {
      setLoading(false);
    }
  };

  if (!country) return null;

  const riskLvl = evnScore ? getRiskLevel(evnScore) : null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      style={{
        borderRadius: 20, overflow: 'hidden', marginBottom: 16,
        background: 'linear-gradient(135deg, #080E1C 0%, #0A1424 100%)',
        border: `1.5px solid ${GOLD}35`,
        boxShadow: `0 4px 32px rgba(0,0,0,0.4), 0 0 0 1px rgba(212,175,55,0.08) inset`,
      }}
    >
      {/* Header — always visible */}
      <button
        onClick={generateBriefing}
        style={{ width: '100%', padding: '16px 20px', display: 'flex', alignItems: 'center', gap: 12, background: 'none', border: 'none', cursor: 'pointer', textAlign: 'left' }}
      >
        <div style={{ width: 40, height: 40, borderRadius: 12, background: `${GOLD}18`, border: `1px solid ${GOLD}40`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
          <Shield style={{ width: 18, height: 18, color: GOLD }} />
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 2 }}>
            <p style={{ margin: 0, fontSize: 13, fontWeight: 800, color: '#fff' }}>
              AI Pre-Departure Safety Briefing
            </p>
            <span style={{ fontSize: 9, fontWeight: 800, padding: '2px 6px', borderRadius: 4, background: `${GOLD}20`, color: GOLD, letterSpacing: '0.08em' }}>
              {briefing?.generatedBy === 'ai' ? 'AI' : briefing ? 'CACHED' : 'NEW'}
            </span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Globe style={{ width: 10, height: 10, color: 'rgba(255,255,255,0.35)' }} />
            <p style={{ margin: 0, fontSize: 11, color: 'rgba(255,255,255,0.45)' }}>
              {country}{procedure ? ` · ${procedure}` : ''} · Personalised for {name}
            </p>
            {riskLvl && (
              <span style={{ fontSize: 10, fontWeight: 700, color: riskLvl.color }}>
                {riskLvl.emoji} {riskLvl.label} Risk
              </span>
            )}
          </div>
        </div>
        {open
          ? <ChevronUp style={{ width: 16, height: 16, color: GOLD, flexShrink: 0 }} />
          : <ChevronDown style={{ width: 16, height: 16, color: GOLD, flexShrink: 0 }} />
        }
      </button>

      {/* Expanded briefing */}
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            style={{ overflow: 'hidden' }}
          >
            <div style={{ padding: '0 20px 20px', borderTop: `1px solid ${GOLD}20` }}>

              {loading ? (
                <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '20px 0', color: 'rgba(255,255,255,0.5)' }}>
                  <Loader2 style={{ width: 16, height: 16, animation: 'spin 1s linear infinite' }} />
                  <span style={{ fontSize: 12 }}>Generating your personalised AI safety briefing for {country}...</span>
                  <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
                </div>
              ) : briefing ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 16, paddingTop: 16 }}>

                  {/* Threat level banner */}
                  {briefing.threatLevel && (() => {
                    const lvlMap = { Low: '#22c55e', Moderate: '#eab308', Elevated: '#f97316', High: '#ef4444' };
                    const c = lvlMap[briefing.threatLevel] || GOLD;
                    return (
                      <div style={{ padding: '8px 14px', borderRadius: 10, background: `${c}12`, border: `1px solid ${c}35`, display: 'flex', alignItems: 'center', gap: 8 }}>
                        <AlertTriangle style={{ width: 13, height: 13, color: c, flexShrink: 0 }} />
                        <span style={{ fontSize: 12, fontWeight: 700, color: c }}>Destination Threat Level: {briefing.threatLevel}</span>
                        {evnScore && <span style={{ fontSize: 10, color: 'rgba(255,255,255,0.3)', marginLeft: 'auto' }}>EVN-iQ400: {evnScore}/100</span>}
                      </div>
                    );
                  })()}

                  {/* Safety precautions */}
                  {briefing.precautions?.length > 0 && (
                    <div>
                      <p style={{ margin: '0 0 8px', fontSize: 10, fontWeight: 800, letterSpacing: '0.12em', color: GOLD }}>SAFETY PRECAUTIONS</p>
                      {briefing.precautions.map((p, i) => (
                        <div key={i} style={{ display: 'flex', gap: 8, marginBottom: 6 }}>
                          <CheckCircle2 style={{ width: 13, height: 13, color: '#22c55e', flexShrink: 0, marginTop: 1 }} />
                          <span style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)', lineHeight: 1.6 }}>{p}</span>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Emergency protocol */}
                  {briefing.emergencyProtocol && (
                    <div style={{ padding: '12px 14px', borderRadius: 12, background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)' }}>
                      <p style={{ margin: '0 0 6px', fontSize: 10, fontWeight: 800, letterSpacing: '0.1em', color: '#ef4444' }}>EMERGENCY PROTOCOL</p>
                      <p style={{ margin: 0, fontSize: 12, color: 'rgba(255,255,255,0.7)', lineHeight: 1.65 }}>{briefing.emergencyProtocol}</p>
                    </div>
                  )}

                  {/* Cultural note + Recovery note */}
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                    {briefing.culturalNote && (
                      <div style={{ padding: '10px 12px', borderRadius: 10, background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)' }}>
                        <p style={{ margin: '0 0 5px', fontSize: 9, fontWeight: 800, color: 'rgba(255,255,255,0.4)', letterSpacing: '0.1em' }}>CULTURAL TIPS</p>
                        <p style={{ margin: 0, fontSize: 11, color: 'rgba(255,255,255,0.6)', lineHeight: 1.6 }}>{briefing.culturalNote}</p>
                      </div>
                    )}
                    {briefing.recoveryNote && (
                      <div style={{ padding: '10px 12px', borderRadius: 10, background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)' }}>
                        <p style={{ margin: '0 0 5px', fontSize: 9, fontWeight: 800, color: GOLD, letterSpacing: '0.1em' }}>RECOVERY PLAN</p>
                        <p style={{ margin: 0, fontSize: 11, color: 'rgba(255,255,255,0.6)', lineHeight: 1.6 }}>{briefing.recoveryNote}</p>
                      </div>
                    )}
                  </div>

                  {/* Footer */}
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', paddingTop: 4 }}>
                    <p style={{ margin: 0, fontSize: 9, color: 'rgba(255,255,255,0.2)' }}>
                      {briefing.generatedBy === 'ai' ? '✨ AI-generated · personalised for your journey' : '📱 Offline briefing · full AI available when online'}
                    </p>
                    <button
                      onClick={() => { setBriefing(null); if (caseId) localStorage.removeItem(CACHE_KEY(caseId)); generateBriefing(); }}
                      style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 10, color: GOLD, fontWeight: 600 }}
                    >
                      ↺ Regenerate
                    </button>
                  </div>
                </div>
              ) : null}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
