export const PASSPORT_COUNTRIES = [
  // Americas
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'TT', name: 'Trinidad & Tobago', flag: '🇹🇹' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩' },
  { code: 'VC', name: 'Saint Vincent & the Grenadines', flag: '🇻🇨' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'AG', name: 'Antigua & Barbuda', flag: '🇦🇬' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { code: 'KN', name: 'Saint Kitts & Nevis', flag: '🇰🇳' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  // Europe
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸' },
  { code: 'BA', name: 'Bosnia & Herzegovina', flag: '🇧🇦' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  // Middle East
  { code: 'TR', name: 'Turkey', flag: '🇹🇷' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
  // Asia
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻' },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'HK', name: 'Hong Kong (SAR)', flag: '🇭🇰' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯' },
  // Africa
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'CG', name: 'Republic of Congo', flag: '🇨🇬' },
  { code: 'CD', name: 'DR Congo', flag: '🇨🇩' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫' },
  { code: 'ST', name: 'São Tomé & Príncipe', flag: '🇸🇹' },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  // Oceania
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'OTHER', name: 'Other Country', flag: '🌍' },
];

export const DESTINATIONS = [
  {
    code: 'VE', name: 'Venezuela', flag: '🇻🇪', island: 'Margarita Island',
    highlight: 'Premier dental & cosmetic hub in the Caribbean',
    color: 'from-blue-500 to-cyan-500',
    timezone: 'UTC-4',
  },
  {
    code: 'CO', name: 'Colombia', flag: '🇨🇴',
    highlight: 'World-class cosmetic surgery at affordable prices',
    color: 'from-yellow-500 to-orange-500',
    timezone: 'UTC-5',
  },
  {
    code: 'DO', name: 'Dominican Republic', flag: '🇩🇴',
    highlight: 'Tropical medical tourism with luxury recovery',
    color: 'from-blue-600 to-indigo-600',
    timezone: 'UTC-4',
  },
  {
    code: 'CU', name: 'Cuba', flag: '🇨🇺',
    highlight: 'Renowned medical expertise at exceptional value',
    color: 'from-red-500 to-rose-500',
    timezone: 'UTC-5',
  },
  {
    code: 'TH', name: 'Thailand', flag: '🇹🇭',
    highlight: 'Asia\'s top medical tourism destination',
    color: 'from-violet-500 to-purple-500',
    timezone: 'UTC+7',
  },
  {
    code: 'TR', name: 'Turkey', flag: '🇹🇷',
    highlight: 'Global leader in dental & hair procedures',
    color: 'from-red-600 to-orange-500',
    timezone: 'UTC+3',
  },
  {
    code: 'MX', name: 'Mexico', flag: '🇲🇽',
    highlight: 'Convenient, high-quality cross-border care',
    color: 'from-green-500 to-emerald-500',
    timezone: 'UTC-6',
  },
  {
    code: 'CR', name: 'Costa Rica', flag: '🇨🇷',
    highlight: 'Eco-luxury medical tourism with JCI-accredited hospitals',
    color: 'from-teal-500 to-green-500',
    timezone: 'UTC-6',
  },
  {
    code: 'BR', name: 'Brazil', flag: '🇧🇷',
    highlight: 'Cosmetic surgery capital of the world',
    color: 'from-green-600 to-yellow-500',
    timezone: 'UTC-3',
  },
  {
    code: 'PA', name: 'Panama', flag: '🇵🇦',
    highlight: 'Growing hub with US-trained specialists',
    color: 'from-sky-500 to-blue-500',
    timezone: 'UTC-5',
  },
];

// Helpers
const VF = (days, notes, reqs=[]) => ({ status: 'visa_free', days, notes, requirements: ['Valid passport (6+ months)', 'Return ticket', ...reqs] });
const EV = (days, notes, reqs=[]) => ({ status: 'evisa', days, notes, requirements: ['Valid passport (6+ months)', 'e-Visa approval', ...reqs] });
const VR = (days, notes, reqs=[]) => ({ status: 'visa_required', days, notes, requirements: ['Valid passport (6+ months)', 'Visa application', 'Bank statements', 'Hotel booking', ...reqs] });
const AC = (days, notes, reqs=[]) => ({ status: 'arrival_card', days, notes, requirements: ['Valid passport (6+ months)', 'Tourist card fee', 'Return ticket', ...reqs] });

// Visa rules matrix: [passportCode][destinationCode]
export const VISA_RULES = {
  // ── United States ──
  US: {
    VE: VF(90, 'Tourist card issued on arrival', ['Proof of funds', 'Hotel booking']),
    CO: VF(90, 'No visa required'),
    DO: AC(30, 'Tourist card required on arrival (~$10 USD)'),
    CU: VR(30, 'Tourist card (Pink card) required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa exemption — 60 days', ['Proof of funds']),
    TR: EV(90, 'e-Visa required — apply at evisa.gov.tr', ['Travel insurance recommended']),
    MX: VF(180, 'No visa required — FMM tourist form on arrival'),
    CR: VF(90, 'No visa required', ['Proof of funds ($100/day)']),
    BR: VF(90, 'No visa required since 2024'),
    PA: VF(180, 'No visa required'),
  },
  // ── Canada ──
  CA: {
    VE: VR(null, 'Visa required for Canadian passport holders', ['Medical invitation letter']),
    CO: VF(90, 'No visa required'),
    DO: AC(30, 'Tourist card required on arrival'),
    CU: VR(30, 'Tourist card required — available online or at departure', ['Tourist card', 'Travel insurance required by Cuba']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: EV(90, 'e-Visa required — apply at evisa.gov.tr'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required since 2024'),
    PA: VF(180, 'No visa required'),
  },
  // ── United Kingdom ──
  GB: {
    VE: VR(null, 'Visa required for UK passport holders', ['Medical invitation letter']),
    CO: VF(90, 'No visa required'),
    DO: AC(30, 'Tourist card required on arrival'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance required by Cuba']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: EV(90, 'e-Visa required — apply at evisa.gov.tr'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(180, 'No visa required'),
  },
  // ── Germany / EU Schengen (representative) ──
  DE: {
    VE: VF(90, 'Short-stay visa exemption for EU/Schengen passports'),
    CO: VF(90, 'No visa required'),
    DO: AC(30, 'Tourist card required on arrival'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: VF(90, 'Visa-free for EU passport holders (except Cyprus)'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(180, 'No visa required'),
  },
  FR: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  ES: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  IT: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  PT: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  NL: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  BE: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  CH: { VE: VF(90,'Schengen-equivalent exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  AT: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  SE: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  NO: { VE: VF(90,'Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  DK: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  FI: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  PL: { VE: VF(90,'EU/Schengen exemption'), CO: VF(90,'No visa required'), DO: AC(30,'Tourist card on arrival'), CU: VR(30,'Tourist card required',['Tourist card','Travel insurance']), TH: VF(60,'60-day exemption'), TR: VF(90,'Visa-free for EU'), MX: VF(180,'No visa required'), CR: VF(90,'No visa required'), BR: VF(90,'No visa required'), PA: VF(180,'No visa required') },
  // ── Australia ──
  AU: {
    VE: VR(null, 'Visa required for Australian passport holders', ['Medical invitation letter']),
    CO: VF(90, 'No visa required'),
    DO: AC(30, 'Tourist card required on arrival'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: EV(90, 'e-Visa required — apply at evisa.gov.tr'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required since 2024'),
    PA: VF(180, 'No visa required'),
  },
  // ── New Zealand ──
  NZ: {
    VE: VR(null, 'Visa required', ['Medical invitation letter']),
    CO: VF(90, 'No visa required'),
    DO: AC(30, 'Tourist card on arrival'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: EV(90, 'e-Visa required'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(180, 'No visa required'),
  },
  // ── Japan ──
  JP: {
    VE: VF(90, 'Visa-free for Japanese passport'),
    CO: VF(90, 'No visa required'),
    DO: VF(30, 'Visa-free'),
    CU: VF(30, 'Visa-free for Japan passport holders'),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: VF(90, 'Visa-free'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(180, 'No visa required'),
  },
  // ── South Korea ──
  KR: {
    VE: VF(90, 'Visa-free for Korean passport'),
    CO: VF(90, 'No visa required'),
    DO: VF(30, 'Visa-free'),
    CU: VF(30, 'Visa-free for Korean passport'),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: VF(90, 'Visa-free'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(180, 'No visa required'),
  },
  // ── Russia ──
  RU: {
    VE: VF(90, 'Visa-free for Russian passport'),
    CO: VR(null, 'Visa required', ['Medical invitation letter']),
    DO: VF(30, 'Visa-free'),
    CU: VF(30, 'Visa-free for Russian passport'),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: VF(60, 'Visa-free for Russian passport'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(90, 'No visa required'),
  },
  // ── Trinidad & Tobago ──
  TT: {
    VE: VF(90, 'CARICOM/Venezuela agreement — visa free', ['Proof of funds']),
    CO: VR(null, 'Visa required for T&T passport holders', ['Medical invitation letter']),
    DO: VF(90, 'Visa-free for CARICOM members'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: EV(60, 'e-Visa or visa on arrival available'),
    TR: EV(30, 'e-Visa available online'),
    MX: VF(180, 'No visa required'),
    CR: VF(30, 'No visa required'),
    BR: VR(null, 'Visa required for T&T passport holders', ['Medical documents']),
    PA: VF(90, 'No visa required'),
  },
  // ── Jamaica ──
  JM: {
    VE: VF(90, 'CARICOM agreement — visa free'),
    CO: VR(null, 'Visa required', ['Medical invitation letter']),
    DO: VF(90, 'Visa-free for CARICOM members'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: EV(30, 'e-Visa required'),
    TR: EV(30, 'e-Visa required'),
    MX: VF(180, 'No visa required'),
    CR: VF(30, 'No visa required'),
    BR: VR(null, 'Visa required', ['Medical invitation letter']),
    PA: VF(90, 'No visa required'),
  },
  // ── Barbados ──
  BB: {
    VE: VF(90, 'CARICOM agreement — visa free'),
    CO: VR(null, 'Visa required', ['Medical invitation letter']),
    DO: VF(90, 'Visa-free for CARICOM members'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: EV(30, 'e-Visa required'),
    TR: EV(30, 'e-Visa required'),
    MX: VF(180, 'No visa required'),
    CR: VF(30, 'No visa required'),
    BR: VR(null, 'Visa required', ['Medical invitation letter']),
    PA: VF(90, 'No visa required'),
  },
  // ── Guyana ──
  GY: {
    VE: VF(90, 'CARICOM agreement — visa free'),
    CO: VR(null, 'Visa required', ['Medical invitation letter']),
    DO: VF(90, 'Visa-free for CARICOM members'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: EV(30, 'e-Visa required'),
    TR: EV(30, 'e-Visa required'),
    MX: VF(180, 'No visa required'),
    CR: VF(30, 'No visa required'),
    BR: VR(null, 'Visa required', ['Medical invitation letter']),
    PA: VF(90, 'No visa required'),
  },
  // ── India ──
  IN: {
    VE: VR(null, 'Visa required for Indian passport holders', ['Medical invitation letter']),
    CO: VR(null, 'Visa required for Indian passport holders', ['Medical invitation letter']),
    DO: VR(null, 'Visa required — unless holding valid US/UK/Schengen/Canada visa', ['Medical invitation letter']),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: AC(15, 'Visa on arrival — 15 days'),
    TR: EV(30, 'e-Visa required — apply at evisa.gov.tr'),
    MX: VR(null, 'Visa required unless holding valid US/Canada/Schengen/UK/Japan visa', ['Valid third-country visa (optional exemption)']),
    CR: VR(null, 'Visa required', ['Medical invitation letter']),
    BR: VR(null, 'Visa required for Indian passport holders', ['Medical invitation letter']),
    PA: VR(null, 'Visa required unless holding valid US/UK/Canada/Australia/Schengen visa', ['Medical invitation letter']),
  },
  // ── China ──
  CN: {
    VE: VR(null, 'Visa required for Chinese passport holders', ['Medical invitation letter']),
    CO: VR(null, 'Visa required', ['Medical invitation letter']),
    DO: VR(null, 'Visa required — unless holding valid US/UK/Schengen/Canada visa', ['Medical invitation letter']),
    CU: VF(30, 'Visa-free for Chinese passport holders'),
    TH: AC(15, 'Visa on arrival — 15 days'),
    TR: EV(30, 'e-Visa required'),
    MX: VR(null, 'Visa required unless holding valid US/Canada/Schengen/UK/Japan visa', ['Valid third-country visa (optional exemption)']),
    CR: VR(null, 'Visa required', ['Medical invitation letter']),
    BR: VR(null, 'Visa required', ['Medical invitation letter']),
    PA: VR(null, 'Visa required unless holding valid US/UK/Canada/Australia/Schengen visa', ['Medical invitation letter']),
  },
  // ── Nigeria ──
  NG: {
    VE: VR(null, 'Visa required for Nigerian passport holders', ['Medical invitation letter']),
    CO: VR(null, 'Visa required', ['Medical invitation letter']),
    DO: VR(null, 'Visa required — unless holding valid US/UK/Schengen/Canada visa', ['Medical invitation letter']),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: EV(60, 'e-Visa required'),
    TR: EV(30, 'e-Visa required'),
    MX: VR(null, 'Visa required unless holding valid US/Canada/Schengen/UK/Japan visa', ['Medical invitation letter']),
    CR: VR(null, 'Visa required', ['Medical invitation letter']),
    BR: VR(null, 'Visa required', ['Medical invitation letter']),
    PA: VR(null, 'Visa required', ['Medical invitation letter']),
  },
  // ── Brazil ──
  BR: {
    VE: VF(90, 'Visa-free for Brazilian passport holders'),
    CO: VF(90, 'No visa required'),
    DO: VF(30, 'Visa-free'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: VF(90, 'Visa-free for Brazilian passport'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'N/A — destination is your home country'),
    PA: VF(90, 'No visa required'),
  },
  // ── Colombia ──
  CO: {
    VE: VF(90, 'Visa-free — bilateral agreement'),
    CO: VF(90, 'N/A — destination is your home country'),
    DO: VF(30, 'Visa-free'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: VF(90, 'Visa-free'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(90, 'No visa required'),
  },
  // ── Argentina ──
  AR: {
    VE: VF(90, 'Visa-free — bilateral agreement'),
    CO: VF(90, 'No visa required'),
    DO: VF(30, 'Visa-free'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: VF(90, 'Visa-free for Argentine passport'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(90, 'No visa required'),
  },
  // ── Mexico ──
  MX: {
    VE: VF(90, 'Visa-free for Mexican passport'),
    CO: VF(90, 'No visa required'),
    DO: VF(30, 'Visa-free'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: EV(90, 'e-Visa required — apply at evisa.gov.tr'),
    MX: VF(180, 'N/A — destination is your home country'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(90, 'No visa required'),
  },
  // ── UAE ──
  AE: {
    VE: VR(null, 'Visa required', ['Medical invitation letter']),
    CO: VF(90, 'Visa-free for UAE passport holders'),
    DO: VF(30, 'Visa-free'),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa exemption — 60 days'),
    TR: EV(90, 'e-Visa required'),
    MX: VF(180, 'No visa required'),
    CR: VF(90, 'No visa required'),
    BR: VF(90, 'No visa required'),
    PA: VF(180, 'No visa required'),
  },
  // ── South Africa ──
  ZA: {
    VE: VR(null, 'Visa required', ['Medical invitation letter']),
    CO: VR(null, 'Visa required', ['Medical invitation letter']),
    DO: VR(null, 'Visa required — unless holding valid US/UK/Schengen/Canada visa', ['Medical invitation letter']),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(30, 'Visa-free — 30 days'),
    TR: EV(30, 'e-Visa required'),
    MX: VR(null, 'Visa required', ['Medical invitation letter']),
    CR: VR(null, 'Visa required', ['Medical invitation letter']),
    BR: VR(null, 'Visa required', ['Medical invitation letter']),
    PA: VR(null, 'Visa required unless holding valid US/UK/Canada/Schengen visa', ['Medical invitation letter']),
  },
  // ── Philippines ──
  PH: {
    VE: VR(null, 'Visa required', ['Medical invitation letter']),
    CO: VR(null, 'Visa required', ['Medical invitation letter']),
    DO: VR(null, 'Visa required — unless holding valid US/UK/Schengen/Canada visa', ['Medical invitation letter']),
    CU: VR(30, 'Tourist card required', ['Tourist card', 'Travel insurance']),
    TH: VF(60, 'Visa-free — 60 days'),
    TR: EV(30, 'e-Visa required'),
    MX: VR(null, 'Visa required unless holding valid US/Canada/Schengen/UK/Japan visa', ['Medical invitation letter']),
    CR: VR(null, 'Visa required', ['Medical invitation letter']),
    BR: VR(null, 'Visa required', ['Medical invitation letter']),
    PA: VR(null, 'Visa required', ['Medical invitation letter']),
  },
};

// Default fallback for unknown passport/destination combos
export function getVisaRule(passportCode, destinationCode) {
  const countryRules = VISA_RULES[passportCode];
  if (countryRules && countryRules[destinationCode]) {
    return countryRules[destinationCode];
  }
  // Generic fallback
  return {
    status: 'visa_required',
    days: null,
    notes: 'Visa requirements may apply — please verify with the official embassy.',
    requirements: ['Valid passport (6+ months)', 'Visa application', 'Bank statements', 'Return ticket', 'Travel insurance', 'Hotel booking'],
  };
}

export const TRAVEL_PURPOSES = [
  { id: 'dental', label: 'Dental Treatment', emoji: '🦷', desc: 'Implants, veneers, full-mouth restoration' },
  { id: 'cosmetic', label: 'Cosmetic Surgery', emoji: '✨', desc: 'Rhinoplasty, facelift, body contouring' },
  { id: 'medical', label: 'Medical Procedure', emoji: '🏥', desc: 'Specialized medical care or surgery' },
  { id: 'recovery', label: 'Recovery Stay', emoji: '🌿', desc: 'Post-procedure rest and recovery' },
  { id: 'wellness', label: 'Wellness Treatment', emoji: '💆', desc: 'IV therapy, regenerative, wellness programs' },
  { id: 'companion', label: 'Companion Travel', emoji: '👫', desc: 'Accompanying a patient as support' },
];

export const EMBASSY_DATA = {
  VE: {
    name: 'Venezuela',
    flag: '🇻🇪',
    embassies: [
      { country: 'United States', city: 'Washington DC', address: '1099 30th St NW, Washington DC 20007', phone: '+1 202-342-2214', website: 'https://eeuu.embajada.gob.ve', processing: '5–10 business days' },
      { country: 'United Kingdom', city: 'London', address: '1 Cromwell Rd, London SW7 2HW', phone: '+44 20 7581 2776', website: 'https://reinounido.embajada.gob.ve', processing: '5–10 business days' },
      { country: 'Canada', city: 'Ottawa', address: '32 Range Rd, Ottawa ON K1N 8J4', phone: '+1 613-235-5151', website: 'https://canada.embajada.gob.ve', processing: '5–15 business days' },
      { country: 'Trinidad & Tobago', city: 'Port of Spain', address: '16 Victoria Ave, Port of Spain', phone: '+1 868-627-9821', website: 'https://trinidadytobago.embajada.gob.ve', processing: '3–7 business days' },
    ],
  },
  CO: {
    name: 'Colombia',
    flag: '🇨🇴',
    embassies: [
      { country: 'United States', city: 'Washington DC', address: '2118 Leroy Pl NW, Washington DC 20008', phone: '+1 202-387-8338', website: 'https://www.colombiaemb.org', processing: '3–10 business days' },
      { country: 'United Kingdom', city: 'London', address: '3 Hans Crescent, London SW1X 0LN', phone: '+44 20 7589 9177', website: 'https://reinounido.embajada.gov.co', processing: '3–10 business days' },
      { country: 'Trinidad & Tobago', city: 'Port of Spain', address: '27 Queen\'s Park East, Port of Spain', phone: '+1 868-628-6750', website: 'https://trinidadytobago.embajada.gov.co', processing: '5–10 business days' },
    ],
  },
  DO: {
    name: 'Dominican Republic',
    flag: '🇩🇴',
    embassies: [
      { country: 'United States', city: 'Washington DC', address: '1715 22nd St NW, Washington DC 20008', phone: '+1 202-332-6280', website: 'https://domrep.org', processing: '2–5 business days' },
      { country: 'United Kingdom', city: 'London', address: '139 Inverness Terrace, London W2 6JF', phone: '+44 20 7727 6285', website: 'https://embajadadominicana.co.uk', processing: '3–7 business days' },
    ],
  },
  TR: {
    name: 'Turkey',
    flag: '🇹🇷',
    embassies: [
      { country: 'e-Visa (Online)', city: 'Online', address: 'evisa.gov.tr — Official Turkish e-Visa Portal', phone: 'N/A', website: 'https://www.evisa.gov.tr', processing: '24–72 hours online' },
      { country: 'United States', city: 'Washington DC', address: '2525 Massachusetts Ave NW, Washington DC 20008', phone: '+1 202-612-6700', website: 'https://washington.emb.mfa.gov.tr', processing: '5–10 business days' },
    ],
  },
  TH: {
    name: 'Thailand',
    flag: '🇹🇭',
    embassies: [
      { country: 'United States', city: 'Washington DC', address: '1024 Wisconsin Ave NW, Washington DC 20007', phone: '+1 202-944-3600', website: 'https://thaiembdc.org', processing: '3–5 business days' },
      { country: 'United Kingdom', city: 'London', address: '29–30 Queen\'s Gate, London SW7 5JB', phone: '+44 20 7589 2944', website: 'https://thaiembassyuk.org.uk', processing: '3–5 business days' },
    ],
  },
};